#!/usr/bin/env bash
cd $HOME/Botf
token="1654420759:AAH4ywtAEfRSwpqnvJML6RBYkH2hZ6z327E"
while(true) do
rm -fr ../.telegram-cli
if [ ! -f ./tg ]; then
echo "=============================================="
echo "TG IS NOT FIND IN FILES BOT"
echo "=============================================="
exit 1
fi
if [ ! $token ]; then
echo "=============================================="
echo -e "\e[1;36mTOKEN IS NOT FIND IN FILE INFO.LUA \e[0m"
echo "=============================================="
exit 1
fi
echo -e "\033[38;5;208m"
echo -e "                                                  "
echo -e "\033[0;00m"
echo -e "\e[36m"
./tg -s ./Bot.lua -p PROFILE --bot=$token
done
